aplepustak/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('users/', include('allauth.urls')),
    path('profile/', include('django.contrib.auth.urls')),
    path('', include('book.urls', namespace='book')),
    re_path(r'media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += staticfiles_urlpatterns()

book/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'book'

urlpatterns = [
    #path('', views.product, name='one'),
    path('', views.product, name='home'),
    path('home/', views.product, name='home'),
    path('about/', views.about, name='about'),
    path('my-profile/', views.Myprofile.as_view(), name='profile'),
    path('sell-book-b12/', views.SellBk_b12.as_view(), name='sell-book-b12'),
    path('sell-book/', views.SellBook.as_view(), name='sell-book'),
    path('terms_and_conditions/', views.t_and_c, name='t_and_c'),
    path('search/', views.search, name='search'),
    path('book/<slug>/', views.BookDetailView.as_view(), name='book_product'),
    path('add-to-cart/<slug>', views.add_to_cart, name='add-to-cart'),
    path('od-summary/', views.buy_now, name='buy-now'),
    path('remove-from-cart/<slug>',
         views.remove_from_cart, name='remove-from-cart'),
    path('order-summary/', views.OrderSummaryView.as_view(), name='od-summary'),
    path('checkout/', views.Checkoutview.as_view(), name='checkout'),
    path('payment/<payment_option>/', views.PaymentView.as_view(), name='payment'),
    path('cancel-order/', views.cancel_order, name='cancel-order'),
    path('request-refund/', views.RefundRequestView.as_view(), name='request-refund'),
    #path('my-orders/', views.MyorderView.as_view(), name='my-orders'),
    path('message/', views.message_new, name='message'),
]

templates/about.html
{% extends 'base.html' %} {% block extra_head %}

    <style type="text/css">
        #at {
            font-size: 21px;
        }

        #kft {
            font-size: 18px;
            line-height: 30px;
        }

        @media screen and (max-width: 600px) {
            #at {
                font-size: 18px;
            }

            #kft {
                font-size: 15px;
                line-height: 25px;
            }
        }
    </style>
{% endblock %} {% block content %}
    <div class="container">
        <div class="pt-2"></div>
        <div class="card pt-1">
            <div class="card-body body-content">
                <h3 class="content text-center pb-3" id="at"><u>About us</u></h3>
                <ul class="pl-4" id="kft">
                    <li id="at"><b>Vision :</b></li>
                    <p class="pt-1 pl-1 abt">We want to reach more than 1 million students accross 10 cities.<br>
                        Finding a
                        secondary books at minimal price is a challenge for every student. From Aplepustak you will get
                        secondary books at best prices.
                    </p>
                    <li id="at"><b>Mission :</b></li>
                    <p class="pt-1 pl-1 abt">We bring students together on this platform who willing to buy and sell
                        their
                        books at the same time. <br> We serve to those students who wants to buy & sell their books at
                        best
                        price.
                    </p>
                    <li id="at"><b>Objective :</b></li>
                    <p class="pt-1 pl-1 abt">A student sell their books at less than 25% of the MRP, at the same time
                        another student purchase same books at more than 70% of the MRP.
                        <br> Due to this both students face financial loss. Considering the problems
                        of the students we bring this platform for students to reduce such losses.
                    </p>
                </ul>
            </div>


        </div>
    </div>
    <div class="pb-2"></div>

{% endblock %} {% block extra_scripts %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css">


    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js"></script>
{% endblock %}

templates/checkout.html
{% extends 'base.html' %} {% block title %}Checkout{% endblock %}
{% block extra_head %}
    <style>
        * {
            margin: auto;
        }

        .container_c form {
            padding: 20px;
            max-width: 75vw;
            background: #fff;
            box-shadow: 0 5px 10px rgba(0, 0, 0, .1);
        }

        .container_c form .row {
            display: flex;
            flex-wrap: wrap;
            gap: 15px;
        }

        .container_c form .row .col {
            flex: 1 1 250px;
        }

        .container_c form .row .col .title {
            font-size: 20px;
            color: #333;
            padding-bottom: 5px;
            text-transform: uppercase;
        }

        .container_c form .row .col .inputBox {
            margin: 15px 0;
        }

        .container_c form .row .col .inputBox span {
            margin-bottom: 10px;
            display: block;
        }

        .container_c form .row .col .inputBox input {
            width: 100%;
            border: 1px solid #ccc;
            padding: 10px 15px;
            font-size: 15px;
            text-transform: none;
        }

        .container_c form .row .col .inputBox input:focus {
            border: 1px solid #000;
        }

        .container_c form .row .col .flex {
            display: flex;
            gap: 15px;
        }

        .container_c form .row .col .flex .inputBox {
            margin-top: 5px;
        }

        .container_c form .row .col .inputBox img {
            height: 34px;
            margin-top: 5px;
            filter: drop-shadow(0 0 1px #000);
        }

        .container_c form .submit-btn {
            width: 100%;
            padding: 12px;
            font-size: 17px;
            background: #e74c3c;
            color: #fff;
            margin-top: 5px;
            cursor: pointer;
        }

    </style>
{% endblock %}
{% block content %}

    <div class="container_c">

        <form method="POST">
            {% csrf_token %}

            <div class="row">

                <div class="col">

                    <h3 class="title">billing address</h3>

                    <div class="inputBox">
                        <span>address :</span>
                        {{ form.address }}
                    </div>

                    <div class="inputBox">
                        <span>Mobile Number :</span>
                        {{ form.contact_no }}
                    </div>

                    <div class="inputBox">
                        <span>city :</span>
                        {{ form.city }}
                    </div>

                    <div class="inputBox">
                        <span>state :</span>
                        {{ form.state }}
                    </div>

                    <div class="inputBox">
                        <span>pin code :</span>
                        {{ form.pin_code }}
                    </div>

                </div>
            </div>

            <input type="submit" value="Proceed to payment" class="submit-btn">

        </form>

    </div>


{% endblock %}

templates/my_ord1.html
{% extends 'base.html' %}
{% block extra_head %}
<style type="text/css">
    .container-fluid {
        margin-top: 200px;
        width: 100%;
        padding: 20px;
        text-align: justify;
        box-sizing: border-box;
        font-size: 18px;
        line-height: 40px;
    }

    p {
        font-size: 14px;
        margin-bottom: 7px;
    }

    .small {
        letter-spacing: 0.5px !important;
    }

    .card-1 {
        box-shadow: 2px 2px 10px 0px #2b292b
    }

    hr {
        background-color: rgba(248, 248, 248, 0.667)
    }

    .bold {
        font-weight: 500
    }

    .change-color {
        color: #cf9d53 !important
    }

    .card-2 {
        box-shadow: 1px 1px 3px 0px rgb(112, 115, 139);
    }

    .fa-circle.active {
        font-size: 8px;
        color: #e3171a
    }

    .fa-circle {
        font-size: 8px;
        color: #aaa
    }

    .rounded {
        border-radius: 2.25rem !important
    }

    .progress-bar {
        background-color: #e3171a !important
    }

    .progress {
        height: 5px !important;
        margin-bottom: 0
    }
</style>
{% endblock %}
{% block content %}


<div class="container-fluid my-5 d-flex justify-content-center">
    <div class="card card-1">
        <div class="card-header bg-white">
            <div class="media flex-sm-row flex-column-reverse justify-content-between">
                <div class="col my-auto">
                    <h4 class="mb-3 mt-3">Thanks for your order, <span class="change-color">{{user.first_name}}</span>
                    </h4>
                </div>
            </div>
        </div>
        <div class="card-body">
            <div class="row justify-content-between mb-3">
                <div class="col-auto">
                    <h6 class="color-1 mb-0 ml-2 change-color">Receipt</h6>
                </div>
                <div class="col-auto"><small></small></div>
            </div>

            <form method="POST" action="{% url 'book:cancel-order' %}">
                {% csrf_token %} {% for pro, od in mylist %}

                <div class="row mb-4">
                    <div class="col cd_col">
                        <div class="card card-2">
                            <div class="card-body">
                                <div class="media">
                                    <div class="sq align-self-center">
                                        <img class="img-fluid my-auto align-self-center mr-2 mr-md-4 pl-0 p-0 m-0 "
                                            src="{{pro.product.book_image1.url}}" alt="{{ pro.product.book_title }}"
                                            width="135" height="135">
                                    </div>
                                    <div class="media-body my-auto text-right">
                                        <div class="row my-auto flex-column flex-md-row">
                                            <div class="col my-auto">
                                                <h6 class="mb-0" id="ptitle" style="text-transform: capitalize;">{{pro.product.book_title }}</h6>
                                            </div>

                                            <div class="col my-auto" id="pqnt"><small>Qty:
                                                    {{ pro.product_quantity }}</small></div>
                                            <div class="col my-auto">
                                                <h6 class="mb-0" id="pprice">&#8377; {{ od.total_od_price }}</h6>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <hr class="my-3">
                                <div class="row">
                                    {% if od.refund_requested %}
                                    <div class="col-md-3 mb-3">
                                        <button class="btn btn-outline-success" type="submit" name="order_id"
                                            value="{{ od.order_id }}" disabled>
                                            Cancel order requested</button>
                                    </div>
                                    {% else %}
                                    <div class="col-md-3 mb-3">
                                        <button class="btn btn-outline-primary" type="submit" name="order_id"
                                            value="{{ od.order_id }}">
                                            Cancel order</button>
                                    </div>
                                    {% endif %}

                                    <div class="col mt-auto">
                                        <div class="progress my-auto">
                                            <div class="progress-bar progress-bar rounded" style="width:35%"
                                                role="progressbar" aria-valuenow="25" aria-valuemin="0"
                                                aria-valuemax="100"></div>
                                        </div>
                                        <div class="media row justify-content-between">
                                            <div class="col-auto text-left"><span><small
                                                        class="text-left mr-sm-2">Ordered</small>
                                                    <i class="fa fa-circle active"></i></span></div>
                                            <!-- <div class="flex-col"><span><small class="text-right mr-sm-2">out for
                                                            delievery</small>
                                                        <i class="fa fa-circle active"></i></span></div>-->
                                            <div class="col-auto flex-col-auto"><span><small
                                                        class="text-right mr-sm-2">Delivered</small>
                                                    <i class="fa fa-circle"></i></span></div>
                                        </div>

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!--This is for 2nd card means second product-->
                </div>
                <!-- endfor -->
                {% endfor %}
            </form>
        </div>
    </div>
</div>

{% endblock %}

templates/my_profile.html
{% extends 'base.html' %} {% block title %}My Profile{% endblock %}
{% block extra_head %}
    <style>
        .ord {
            overflow-x: hidden;
            font-size: 2vh;
            padding: auto;
        }

        .container_od {
            background: #fff;
            width: 95vw;
            height: 100vh;
            margin: auto;
            position: relative;
            margin-top: 5%;
            box-shadow: 2px 5px 20px rgba(119, 119, 119, .5);
        }

        .leftbox {

            position: absolute;
            width: 95vw;
            height: 10vh;
            background: var(--primaryColor);
            box-shadow: 3px 3px 10px rgba(119, 119, 119, .5);
            border: .1em solid #fff;
            display: flex;
            justify-content: space-evenly;
            flex-direction: column;
        }

        a.tab {
            display: flex;
            justify-content: space-evenly;
            align-items: center;
            align-content: center;
        }

        nav {
            display: flex;
            flex-direction: row;
            justify-content: space-around;
        }

        nav a {
            list-style: none;
            padding-top: 5vh;
            padding-bottom: 5vh;
            color: #fff;
            font-size: 1.1rem;
            display: block;
            transition: all .3s ease-in-out;
        }

        nav a:hover {
            color: white;
            cursor: pointer;
            transform: scale(1.2);

        }


        nav a.active {
            color: black;
        }

        .rightbox {
            width: 95vw;
            margin-left: 5vw;
            padding-top: 10vh;

        }


        h1 {
            font-family: 'Poppins', sans-serif;
            color: var(--primaryColor);
            font-size: 5vh;
            margin-top: 1vh;
            margin-bottom: 2vh;


        }

        h2 {
            color: #777;
            font-family: 'Poppins', sans-serif;
            text-transform: uppercase;
            font-size: 3vh;
            letter-spacing: 1px;
            margin-left: 2px;
            margin-top: 10px;

        }

        .input,
        p {
            border: 0;
            border-bottom: 1px solid var(--primaryColor);
            width: 80%;
            font-family: 'Poppins', sans-serif;
            font-size: 2vh;
            padding: 7px 0;
            color: #070707;
            outline: none;

        }

        span {
            font-size: .7em;
            color: #777;
        }


        .tabShow {
            transition: all .5s ease-in;
            width: 90%;
            height: 90%;
            position: absolute;
        }

        .tableContainerDiv {
            overflow: auto;
            height: 80%;

        }

        table {
            font-family: 'Poppins', sans-serif;
            /* border-collapse: collapse; */
            position: relative;
            width: 100%;

        }

        th {
            background-color: var(--primaryColor);
            position: sticky;
            top: 0;
            padding: 5px;
            text-align: left;

        }

        td {
            text-align: left;
            padding: 8px;
        }

        tr:nth-child(even) {
            background-color: #dddddd;
        }
    </style>
{% endblock %}
{% block content %}
    <body class="ord">
    <div class="container_od">
        <div class="leftbox">
            <nav>
                <a onclick="tabs(0)" class="tab active">
                    <i class="fa fa-user fa-4x"></i>

                </a>

                <a onclick="tabs(1)" class="tab">
                    <i class="fa fa-credit-card fa-4x"></i>
                </a>

                <a href="/profile/logout/" onclick="tabs(3)" class="tab"><i class="fa fa-power-off fa-4x"
                                                                            title="Logout"></i></a>
            </nav>
        </div>
        <div class="rightbox">
            <div class="profile tabShow">
                <h1>Personal Info</h1>
                <h2>Full Name</h2>
                <input type="email" class="input" value="{{ user.first_name }}" readonly>
                <h2>Contact number</h2>
                <input type="gender" class="input" value="{{ pro.contact_no }}" readonly>
                <h2>Email</h2>
                <input type="email" class="input" value=" {{ user.email }}" readonly>
                <h2>Refer code</h2>
                <input type="email" class="input" value="{{ pro.refer_code }}" readonly>
                <br>
            </div>
            <div class="tabShow ">
                <h1>Order Details</h1>
                <div class="tableContainerDiv ">
                    <table>
                        <tr>
                            <th>Order Id</th>
                            <th>Products</th>
                            <th>Total Price</th>
                            <th>Ordered date</th>
                            <th>Delivery date</th>

                        </tr>
                        {% for pro, od in mylist %}
                            <tr>
                                <td>{{ od.order_id }}</td>
                                <td>{{ pro.product.book_title }}-{{ pro.product_quantity }}</td>
                                <td>₹ {{ od.total_od_price }}</td>
                                <td>{{ od.ordered_date }}</td>
                                {% if od.delivery_date %}
                                    <td>{{ od.delievery_date }}</td>
                                {% else %}
                                    <td>Coming soon..</td>
                                {% endif %}
                            </tr>
                        {% endfor %}
                    </table>
                </div>
            </div>


        </div>
    </div>

    </body>
{% endblock %}
{% block extra_scripts %}
    <script>
        const tabBtn = document.querySelectorAll(".tab");
        const tab = document.querySelectorAll(".tabShow");

        function tabs(panelIndex) {
            tab.forEach(function (node) {
                node.style.display = "none";
            });
            tab[panelIndex].style.display = "block";
        }

        tabs(0);

        $(".tab").click(function () {
            $(this).addClass("active").siblings().removeClass("active");
        })
    </script>
    
{% endblock %}

templates/order_summary.html
{% extends 'base.html' %}{% load static %}
{% block title %}My cart{% endblock %}
{% block extra_head %}
    <style>

        /*
    ======================
    Cart Area
    ======================
    */

        section {
            margin: auto;
        }

        .page__title-area {
            background-color: var(--primaryColor);
        }


        .page__title-container {
            padding: 1rem;
        }

        .page__titles {
            display: flex;
            align-items: center;
            font-size: 1.2rem;
            color: var(--grey2);
        }

        .page__titles a {
            margin-right: 2rem;
        }

        .page__titles a svg {
            width: 1.8rem;
            height: 1.8rem;
            fill: var(--grey2);
        }

        .page__title {
            position: relative;
        }

        .page__title::before {
            position: absolute;
            content: "/";
            top: 0;
            left: -1rem;
        }


        table {
            width: 100%;
            border-collapse: collapse;
        }

        .cart-info {
            display: flex;
            flex-wrap: wrap;
        }

        .cart-page {
            max-width: 117rem;
            margin: auto;
        }

        th {
            text-align: left;
            padding: 5px;
            color: #fff;
            background: #e74c3c;
            font-weight: normal;
        }

        td {
            padding: 10px 10px;
        }

        td input {
            width: 40px;
            height: 30px;
            padding: 5px;
        }

        td a {
            color: #e74c3c;
            font-size: 15px;
        }

        td img {
            width: 100px;
            height: 100px;
            margin-right: 10px;
        }

        .total-price {
            display: flex;
            justify-content: flex-end;
        }

        .total-price table {

            border-bottom: 3px solid #e74c3c;
            width: 100%;
            max-width: 100vh;
        }

        .Total-Price-border {
            border-top: 3px solid #e74c3c;
        }

        td:last-child {
            text-align: right;
        }

        th:last-child {
            text-align: right;
        }


        .hero__btn {
            display: inline-block;
            font-weight: 700;
            font-size: 1.4rem;
            background-color: var(--black);
            color: var(--primaryColor);
            cursor: pointer;
            margin-top: 1rem;
            padding: 1.5rem 4rem;
            border: 1px solid var(--black);
            transition: all 0.3s ease-in-out;
        }

        th:nth-child(2) {
            text-align: center;
        }

    </style>
{% endblock %}
{% block content %}


    <div class="page__title-area">
        <div class="container">
            <div class="page__title-container">
                <ul class="page__titles">
                    <li>
                        <a href="/home">
                            <img src="{% static './images/icons/home.svg' %}"/>
                        </a>
                    </li>
                    <li class="page__title">Cart</li>
                </ul>
            </div>
        </div>
    </div>

    {% if user.is_authenticated %}
        <main id="main" class="container_od_summary">

            <!---cart-item-details---->

            <section class="cart-page">



                <table>
                    <tr>
                        <th>Products</th>
                        <th>Quantity</th>
                        <th>Subtotal</th>

                    </tr>
                    {% for order_product in object.products.all %}
                        <tr>
                            <td>
                                <div class="cart-info">
                                    <img src="{{ order_product.product.book_image1.url }}"
                                         alt="{{ order_product.product.book_title }}">
                                </div>
                                <div><br>
                                    <p>{{ order_product.product.book_title }}</p>

                                    <small> Price: {% if order_product.product.book_discount_price %} &#8377
                                        {{ order_product.product.book_discount_price }} {% else %} &#8377
                                        {{ order_product.product.book_price }} {% endif %}</small>
                                    <br>
                                    <a href="{% url 'book:remove-from-cart' order_product.product.slug %}">Remove</a>
                                </div>
                            </td>
                            <td style=" text-align:center;">
                            <span type="text" value="1"
                                  class="counter-btn">{{ order_product.product_quantity }}</span>
                            </td>

                            <td>{% if order_product.product.book_discount_price %} &#8377
                                {{ order_product.get_pro_discount_price }}{% else %} &#8377
                                {{ order_product.get_pro_price }}
                            {% endif %}</td>
                        </tr>
                    {% endfor %}


                </table>
                {% if object.total_od_price %}
                    <div class="total-price"
                         style="border-top:3px solid #ff523b;display: flex; flex-direction: row; justify-content: space-between;">
                        <div style="display: flex; flex-direction: column; justify-content: space-around; margin: 5px">
                            <a href="/home">
                                <button class="hero__btn"
                                        style="color: whitesmoke; display: flex; justify-content: space-around; background-color: #e74c3c;">
                                    Continue shopping
                                </button>
                            </a>
                            <a href="/checkout">
                                <button class="hero__btn"
                                        style="color:black;display: flex; justify-content: space-around; background-color: var(--primaryColor);">
                                    Proceed
                                    To Checkout
                                </button>
                            </a>

                        </div>

                        <table style="border-left: 3px solid #ff523b;
                    border-right: 3px solid #ff523b;">
                            <tr>
                                <td>
                                    Subtotal
                                </td>
                                <td>
                                    &#8377 {{ object.get_total }}
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    delivery charges
                                </td>
                                <td>
                                    &#8377 {{ object.get_total_delievery_charges }}
                                </td>
                            </tr>
                            <tr class="Total-Price-border">
                                <td>
                                    Total
                                </td>
                                <td>
                                    &#8377 {{ object.total_od_price }}
                                </td>
                            </tr>
                        </table>
                    </div>

                {% endif %}
            </section>
        </main>
    {% endif %}
{% endblock %}
{% block extra_scripts %}

{% endblock %}

templates/request_refund.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<div class="container">
    <h2>Refund Request</h2>
    <form method="POST" action="{% url 'book:request-refund' %}">
        {% csrf_token %}
        <label for="room_no" class="ml-0">Order ID :-</label>
        <input type="text" value={{od_id}} name="order_id" readonly>
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>

</div>

{% endblock %}